// <auto-generated />
namespace Trabalho.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class hehehehe911 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hehehehe911));
        
        string IMigrationMetadata.Id
        {
            get { return "201801061850371_hehehehe~911"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
